# Usando a imagem oficial do Node.js
FROM node:16

# Diretório de trabalho dentro do container
WORKDIR /usr/src/app

# Copiar os arquivos de configuração do projeto para dentro do container
COPY package*.json ./

# Instalar dependências
RUN npm install

# Copiar o código-fonte do projeto para o container
COPY . .

# Expôr a porta em que a aplicação irá rodar
EXPOSE 3001

# Comando para rodar a aplicação
CMD ["npm", "start"]
